services:
  - type: web
    name: netflix-recommendation
    env: python
    pythonVersion: 3.11
    buildCommand: pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn --workers 1 --timeout 60 --max-requests 1000 --bind 0.0.0.0:10000 app:app
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
